version: '3'
services:
  nginx:
    image: nginx
    volumes:
     - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"

  node_web_server:
    build:
      context: .
      dockerfile: ./containers/node/Dockerfile
    depends_on:
     - nginx
    user: "node"
    working_dir: "/app"
    environment:
     - NODE_ENV=production
    volumes:
     - ./:/app
     - /app/node_modules
    expose:
     - "8081"
    command: "node index.js"
